apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeeprofilemanagement-deployment
  namespace: employeeprofilemanagement-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employeeprofilemanagement
  template:
    metadata:
      labels:
        app: employeeprofilemanagement
    spec:
      containers:
        - name: employeeprofilemanagement-container
          image: employeeprofilemanagement_image:34
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8200
