apiVersion: v1
kind: Service
metadata:
  name: employeeprofilemanagement-service
  namespace: employeeprofilemanagement-ns
spec:
  type: NodePort
  selector:
    app: employeeprofilemanagement
  ports:
    - port: 8200        # Cluster IP port
      targetPort: 8200  # Container port
      nodePort: 30082   # Port accessible from Postman
