apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: employee
spec:
  type: NodePort
  selector:
    app: employee
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
